import org.testng.annotations.*;
import static org.testng.Assert.*;
import java.io.ByteArrayInputStream;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library --with testng'
 * by 'Karanjit_Singh' at '8/2/17 11:41 AM' with Gradle 3.1
 *
 * @author Karanjit_Singh, @date 8/2/17 11:41 AM
 */

public class HelloNameTests {

    @DataProvider(name="names")
    public Object[][] names() {
        return new Object[][] {
                {"Steven"},
                {"Steve"},
                {"Stefan"},
                {"Stephanie"}
        };
    }

    @Test(dataProvider = "names")
    public void appGreetsByName(String name) {
        HelloName classUnderTest = new HelloName();
        assertEquals(classUnderTest.getGreetings(name), "Hello "+name, "app should greet by name");
    }

    @Test public void whetherGreetedNameIsTheOneWeHaveGiven() {
        // given
        HelloName a = new HelloName();
        System.setIn(new ByteArrayInputStream("A fancy name".getBytes()));
        String nameWeGave = a.askUserForAName();
        // when
        String nameWeGreet = a.getGreetings(nameWeGave);

        // then
        assertEquals(nameWeGreet, "Hello " + nameWeGave);
    }


}